export const GET_ALL_NEWS = "GET_ALL_NEWS";

export const HANDLE_SEARCH = "HANDLE_SEARCH";

export const DELETE_SINGLE_NEWS = "DELETE_SINGLE_NEWS";
export const DELETE_ALL_NEWS = "DELETE_ALL_NEWS";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const SET_CURRENT_NEWS_OBJECT = "SET_CURRENT_NEWS_OBJECT";
export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";
